version: '3'
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm start

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm start